### ISSUE TITLE
Template Editor:  When I attempted to delete the template it asked would you like to delete followed by a window asking if I wanted to save my work.

### ISSUE THREAD

**Issue by RowanDarlison** [Rise-Vision/rise-vision-apps#969]
**Steps to recreate:**
(only happens if template is not used in a schedule otherwise it shows the msg that the template is used in a schedule and cannot be deleted)
1. Add Presentation.
2. Save presentation
3. Change Presentation
4. Delete presentation
5. Notification - “Are you sure you want to delete this presentation”
6. Clicked delete forever
7. Notification - “Do you want to save changes before leaving? Your changes will be lost if you don’t save them.” given options; save, don’t save, cancel.
8. Clicked save - nothing happened
9. Clicked don’t save - presentation deleted.
10. Clicked cancel - app breaks and template turns white, when buttons are clicked you see a white screen with words "AccessDeniedAccess denied.Anonymous caller does not have storage.objects.get access to widgets.risevision.com/stable/templates/undefined/src/template.html.". Can’t click back.

**Comment by alex-deaconu** [comment]
@RowanDarlison this issue should now be resolved. Thanks!

**Comment by RowanDarlison** [comment]
Hey @alex-deaconu I went through the same steps and all the errors are still happening.

**Comment by alex-deaconu** [comment]
@RowanDarlison wondering if you cleared your cache before testing this? I just tried it again and I don't get any notifications. Thanks.

**Comment by RowanDarlison** [comment]
Yes sorry looks good now!
